# Generated by Django 5.1.3 on 2025-11-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="last_voted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
